-- Tabla NUTS (Nomenclatura de Unidades Territoriales Estadísticas) para España
-- Datos estáticos correspondientes a la clasificación NUTS de Eurostat

CREATE TABLE IF NOT EXISTS dim.nuts_spain (
    geocode VARCHAR(10) PRIMARY KEY,
    etiqueta VARCHAR(100) NOT NULL
);

-- Insertar datos NUTS
INSERT INTO dim.nuts_spain (geocode, etiqueta) VALUES
('ES1', 'Noroeste'),
('ES2', 'Noreste'),
('ES3', 'Comunidad de Madrid'),
('ES4', 'Centro (E)'),
('ES5', 'Este'),
('ES6', 'Sur'),
('ES7', 'Canarias'),
('ES11', 'Galicia'),
('ES12', 'Principado de Asturias'),
('ES13', 'Cantabria'),
('ES21', 'País Vasco'),
('ES22', 'Comunidad Foral de Navarra'),
('ES23', 'La Rioja'),
('ES24', 'Aragón'),
('ES30', 'Comunidad de Madrid'),
('ES41', 'Castilla y León'),
('ES42', 'Castilla-La Mancha'),
('ES43', 'Extremadura'),
('ES51', 'Cataluña'),
('ES52', 'Comunidad Valenciana'),
('ES53', 'Illes Balears'),
('ES61', 'Andalucía'),
('ES62', 'Región de Murcia'),
('ES63', 'Ciudad Autónoma de Ceuta'),
('ES64', 'Ciudad Autónoma de Melilla'),
('ES70', 'Canarias'),
('ES111', 'A Coruña'),
('ES112', 'Lugo'),
('ES113', 'Ourense'),
('ES114', 'Pontevedra'),
('ES120', 'Asturias'),
('ES130', 'Cantabria'),
('ES211', 'Álava'),
('ES212', 'Guipúzcoa'),
('ES213', 'Vizcaya'),
('ES220', 'Navarra'),
('ES230', 'La Rioja'),
('ES241', 'Huesca'),
('ES242', 'Teruel'),
('ES243', 'Zaragoza'),
('ES300', 'Madrid'),
('ES411', 'Ávila'),
('ES412', 'Burgos'),
('ES413', 'León'),
('ES414', 'Palencia'),
('ES415', 'Salamanca'),
('ES416', 'Segovia'),
('ES417', 'Soria'),
('ES418', 'Valladolid'),
('ES419', 'Zamora'),
('ES421', 'Albacete'),
('ES422', 'Ciudad Real'),
('ES423', 'Cuenca'),
('ES424', 'Guadalajara'),
('ES425', 'Toledo'),
('ES431', 'Badajoz'),
('ES432', 'Cáceres'),
('ES511', 'Barcelona'),
('ES512', 'Girona'),
('ES513', 'Lleida'),
('ES514', 'Tarragona'),
('ES521', 'Alicante / Alacant'),
('ES522', 'Castellón / Castelló'),
('ES523', 'Valencia / València'),
('ES530', 'Illes Balears'),
('ES611', 'Almería'),
('ES612', 'Cádiz'),
('ES613', 'Córdoba'),
('ES614', 'Granada'),
('ES615', 'Huelva'),
('ES616', 'Jaén'),
('ES617', 'Málaga'),
('ES618', 'Sevilla'),
('ES620', 'Murcia'),
('ES630', 'Ceuta'),
('ES640', 'Melilla'),
('ES701', 'Las Palmas'),
('ES702', 'Santa Cruz de Tenerife')
-- Códigos NO oficiales pero necesarios para mapeo de nombres exactos de islas Canarias y Baleares
('ES703', 'El Hierro'),
('ES704', 'Fuerteventura'),
('ES705', 'Gran Canaria'),
('ES706', 'La Gomera'),
('ES707', 'La Palma'),
('ES708', 'Lanzarote'),
('ES709', 'Tenerife'),
('ES531', 'Mallorca'),
('ES532', 'Menorca'),
('ES533', 'Eivissa y Formentera')
ON CONFLICT (geocode) DO NOTHING;
