-- Tabla de política de gastos para subvenciones
-- Datos estáticos que no cambiarán

CREATE TABLE IF NOT EXISTS dim.politica_gastos (
    id INTEGER PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL
);

-- Insertar políticas de gastos
INSERT INTO dim.politica_gastos (id, descripcion) VALUES
(1, 'JUSTICIA'),
(2, 'DEFENSA'),
(3, 'SEGURIDAD CIUDADANA E INSTITUCIONES PENITENCIARIAS'),
(4, 'OTRAS PRESTACIONES ECONÓMICAS'),
(5, 'SERVICIOS SOCIALES Y PROMOCIÓN SOCIAL'),
(6, 'FOMENTO DEL EMPLEO'),
(7, 'DESEMPLEO'),
(8, 'ACCESO A LA VIVIENDA Y FOMENTO DE LA EDIFICACIÓN'),
(9, 'SANIDAD'),
(10, 'EDUCACIÓN'),
(11, 'CULTURA'),
(12, 'AGRICULTURA, PESCA Y ALIMENTACIÓN'),
(13, 'INDUSTRIA Y ENERGÍA'),
(14, 'COMERCIO, TURISMO Y PYMES'),
(15, 'SUBVENCIONES AL TRANSPORTE'),
(16, 'INFRAESTRUCTURAS'),
(17, 'INVESTIGACIÓN, DESARROLLO E INNOVACIÓN'),
(18, 'OTRAS ACTUACIONES DE CARÁCTER ECONÓMICO'),
(19, 'SIN INFORMACION ESPECIFICA'),
(20, 'COOPERACIÓN INTERNACIONAL PARA EL DESARROLLO Y CULTURAL'),
(21, 'INFORMACIÓN NO DISPONIBLE')
ON CONFLICT DO NOTHING;
